/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3730A3',
          container: '#4F4BBC',
          fixed: '#E2DFFF',
          'fixed-dim': '#C3C0FF',
        },
        'on-primary': {
          DEFAULT: '#FFFFFF',
          container: '#D0CDFF',
          fixed: '#0F0069',
          'fixed-variant': '#3B35A7',
        },
        secondary: {
          DEFAULT: '#505F76',
          container: '#D0E1FB',
          fixed: '#D3E4FE',
          'fixed-dim': '#B7C8E1',
        },
        'on-secondary': {
          DEFAULT: '#FFFFFF',
          container: '#54647A',
          fixed: '#0B1C30',
          'fixed-variant': '#38485D',
        },
        tertiary: {
          DEFAULT: '#6C3400',
          container: '#8F4700',
          fixed: '#FFDCC6',
          'fixed-dim': '#FFB784',
        },
        'on-tertiary': {
          DEFAULT: '#FFFFFF',
          container: '#FFC7A2',
          fixed: '#301400',
          'fixed-variant': '#713700',
        },
        surface: {
          DEFAULT: '#F7F9FB',
          bright: '#F7F9FB',
          dim: '#D8DADC',
          container: '#ECEEF0',
          'container-high': '#E6E8EA',
          'container-highest': '#E0E3E5',
          'container-low': '#F2F4F6',
          'container-lowest': '#FFFFFF',
          tint: '#544FC0',
          variant: '#E0E3E5',
        },
        'on-surface': {
          DEFAULT: '#191C1E',
          variant: '#454652',
        },
        background: '#F7F9FB',
        'on-background': '#191C1E',
        error: {
          DEFAULT: '#BA1A1A',
          container: '#FFDAD6',
        },
        'on-error': {
          DEFAULT: '#FFFFFF',
          container: '#93000A',
        },
        outline: {
          DEFAULT: '#757684',
          variant: '#C5C5D4',
        },
        inverse: {
          surface: '#2D3133',
          'on-surface': '#EFF1F3',
          primary: '#C3C0FF',
        },
      },
      fontFamily: {
        'manrope': ['Manrope_400Regular', 'sans-serif'],
        'manrope-medium': ['Manrope_500Medium', 'sans-serif'],
        'manrope-semibold': ['Manrope_600SemiBold', 'sans-serif'],
        'manrope-bold': ['Manrope_700Bold', 'sans-serif'],
        'inter': ['Inter_400Regular', 'sans-serif'],
        'inter-medium': ['Inter_500Medium', 'sans-serif'],
        'inter-semibold': ['Inter_600SemiBold', 'sans-serif'],
      },
      fontSize: {
        'display': ['56px', { lineHeight: '64px', letterSpacing: '-0.32px', fontWeight: '700' }],
        'display-sm': ['36px', { lineHeight: '44px', letterSpacing: '-0.2px', fontWeight: '700' }],
        'headline': ['28px', { lineHeight: '36px', letterSpacing: '-0.16px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '500' }],
        'title': ['18px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '500' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body': ['14px', { lineHeight: '20px', letterSpacing: '0.14px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '600' }],
        'label': ['12px', { lineHeight: '16px', letterSpacing: '0.36px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '600' }],
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '32px',
        'full': '9999px',
      },
      spacing: {
        '0.5': '4px',
        '1': '8px',
        '1.5': '12px',
        '2': '16px',
        '3': '24px',
        '4': '32px',
        '5': '40px',
        '6': '48px',
        '8': '64px',
        '10': '80px',
      },
    },
  },
  plugins: [],
};
